package com.food.servlet;

import java.io.IOException;
import java.time.LocalDateTime;

import com.food.dao.OrderItemDAO;
import com.food.dao.OrdersDAO;
import com.food.daoimpl.OrderItemDAOImpl;
import com.food.daoimpl.OrdersDAOImpl;
import com.food.model.Cart;
import com.food.model.CartItem;
import com.food.model.OrderItem;
import com.food.model.Orders;
import com.food.model.Restaurant;
import com.food.model.User;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

@WebServlet("/CheckoutServlet")
public class CheckoutServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    private OrdersDAO    ordersDAO    = new OrdersDAOImpl();
    private OrderItemDAO orderItemDAO = new OrderItemDAOImpl();

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();

        User user = (User) session.getAttribute("loggedUser");
        Cart cart = (Cart) session.getAttribute("cart");

        if (user == null) {
            response.sendRedirect("login.jsp");
            return;
        }
        
        if (cart == null || cart.getItems().isEmpty()) {
            response.sendRedirect("cart.jsp?error=empty");
            return;
        }

        // 🛡️ Fail-safe: Validate that all items belong to the EXACT same restaurant
        int restaurantId = cart.getItems().get(0).getMenu().getRestaurant().getRestaurantID();
        for (CartItem item : cart.getItems()) {
            if (item.getMenu().getRestaurant().getRestaurantID() != restaurantId) {
                cart.clearCart();
                response.sendRedirect("cart.jsp?error=corrupted");
                return;
            }
        }

        Orders order = new Orders();

        // ✅ REMOVED: order.setOrderID(...) — ID is auto-generated by the DB (@GeneratedValue)
        //    Setting a manual ID before persist() causes Hibernate errors.

        order.setUser(user);

        Restaurant restaurant = cart.getItems().get(0).getMenu().getRestaurant();
        order.setRestaurant(restaurant);

        order.setOrderDate(LocalDateTime.now());
        order.setTotalAmount(cart.getGrandTotal());
        order.setStatus("PLACED");
        order.setPaymentMethod(request.getParameter("paymentMethod"));

        // Persist the order first — Hibernate will assign an auto-generated orderID
        ordersDAO.placeOrder(order);

        // Now persist each OrderItem (each references the saved order)
        for (CartItem cartItem : cart.getItems()) {

            OrderItem orderItem = new OrderItem();

            // ✅ REMOVED: orderItem.setOrderItemID(...) — ID is auto-generated
            orderItem.setOrder(order);
            orderItem.setMenu(cartItem.getMenu());
            orderItem.setQuantity(cartItem.getQuantity());
            orderItem.setItemTotal(cartItem.getTotalPrice());

            orderItemDAO.addOrderItem(orderItem);
        }

        // Clear the session cart after successful checkout
        cart.clearCart();

        // Redirect to the orders page
        response.sendRedirect("OrderServlet");
    }
}