package com.food.servlet;

import java.io.IOException;
import java.time.LocalDateTime;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import com.food.dao.UserDAO;
import com.food.daoimpl.UserDAOImpl;
import com.food.model.User;

@WebServlet("/register")
public class RegisterServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    private UserDAO userDAO = new UserDAOImpl();

    @Override
    protected void doPost(HttpServletRequest request,
                          HttpServletResponse response)
            throws ServletException, IOException {

        try {
            String email = request.getParameter("email");

            // Check duplicate email before inserting
            if (userDAO.emailExists(email)) {
                request.setAttribute("error", "Email is already registered. Please login.");
                request.getRequestDispatcher("register.jsp").forward(request, response);
                return;
            }

            User user = new User();

            // ✅ REMOVED: user.setUserID(...) — ID is auto-generated by the DB (@GeneratedValue)
            //    Setting a manual ID before persist() causes a "detached entity" error in Hibernate.

            user.setUsername(request.getParameter("username"));
            user.setPassword(request.getParameter("password")); // Hash in production!
            user.setEmail(email);
            user.setAddress(request.getParameter("address"));
            user.setRole("CUSTOMER");
            user.setCreateDate(LocalDateTime.now());
            user.setLastLoginDate(LocalDateTime.now());

            userDAO.addUser(user);

            response.sendRedirect("login.jsp");

        } catch (Exception e) {
            e.printStackTrace();
            request.setAttribute("error", "Registration failed. Please try again.");
            request.getRequestDispatcher("register.jsp").forward(request, response);
        }
    }
}